FEAT: 얼루가게 회원가입 화면 퍼블리싱
the-kingdoms/eollugage-fe pull request #12
Opened 2024-10-04 12:39 UTC by yerim08

## #️연관된 이슈

> #5

- 전화번호로 시작하기는 바텀 시트 추가해서 다시 수정 필요
- 회원가입 스텝을 처리할 때 각 폴더 내에 [step]으로 두고 한 페이지 내에서 조건부 처리로 개발을 했는데 코드가 좀 복잡하고 길어지는 것 같아서 좋은 의견 있으시면 리뷰 부탁드립니다 !

2024-10-05 14:47 UTC, iOdiO89 requested changes
1.

2024-10-05 15:49 UTC, iOdiO89 requested changes
다른 부분은 크게 문제될 것이 없어보입니다! 파일 구조에 대해 제 생각을 말씀드리자면, dynamic route는 보통 데이터/유저별로 다른 페이지를 만들기 위해서 사용하는데요..! step 정보는 굳이 dynamic route에 담아야하나 싶은 느낌은 있습니다. 

1. dynamic route를 사용하고 싶으시다면 
- 첫 화면에서 '전화번호로 시작하기' 누르면 바로 바텀시트 올라오기(login button 컴포넌트를 수정하면 될 것 같습니다)
- /app/join : 얼루가게 출입증 화면(직원/사장 선택화면)
- /app/join/[method]/[position]/[name]/... 이런식으로 각 화면에서 받아오는 정보들을 Path로 받아서 사용하면 어떨까 싶습니다

2024-10-05 15:49 UTC, iOdiO89 commented on src/app/join/phone/page.tsx
전화번호, 이름 입력 화면은 바텀시트라서요! 화면 자체를 컴포넌트로 분리해주시고, 로그인버튼 onclick을 좀 수정해서 바로 바텀시트가 띄워지는 게 좋을 것 같습니다

2024-10-05 15:49 UTC, iOdiO89 commented on src/features/join/utils/getRandomColor.tsx
> +  | undefined {
이렇게 리턴값을 적으면 colors에 없는 값도 반환이 되나요?

2024-10-05 15:49 UTC, iOdiO89 commented on src/features/join/utils/getRandomColor.tsx
> +  return colors[randomIndex] || undefined // 반환되지 않을 경우 undefined 허용
undefined는 반환이 안 되게 막는 것이 ...!! 어떨까요

2024-10-05 15:49 UTC, iOdiO89 commented on src/widgets/join/ui/BadgeCard.tsx
> +            </svg>
얼루가게 출입증 svg 파일인거죠? /public/images 폴더로 분리해주시고 사용해주세요! 제가 svg 사용 설정을 따로 안 해놔서, typescript + svg 같이 검색하셔서 사용법 확인해보시면 좋을 것 같습니다

2024-10-05 15:49 UTC, iOdiO89 commented on src/widgets/join/ui/BadgeCard.tsx
> +        <div className="body-05-bold-compact text-white pl-spacing-05 mt-[108px]">
```suggestion
<div className="body-05-bold-compact text-text-on-color pl-spacing-05 mt-[108px]">
```

2024-10-05 15:49 UTC, iOdiO89 commented on src/app/join/phone/page.tsx
> +        <ButtonMobile size="L" style="primary" state="enabled" type="text" text1="시작하기" />
이름, 전화번호가 입력되지 않았을 때는 disabled 설정해주시고, 버튼 누르면 얼루가게 출입증 있는 페이지로 이동하게 하면 될 것 같습니다!

2024-10-05 15:49 UTC, iOdiO89 commented on src/widgets/index.ts
이건 그냥 파일 생성하시려고 만드신건가요? 어떤 의미가 있나용

2024-10-05 15:49 UTC, iOdiO89 commented on src/widgets/join/ui/bottomSheet.tsx
> +        <div className="w-[40px] h-[4px] items-center rounded-[1000px] bg-[#E0E0E0] mb-spacing-04" />
```suggestion
<div className="w-10 h-1 items-center rounded-full bg-button-secondary mb-spacing-04" />
```

2024-10-05 15:49 UTC, iOdiO89 commented on src/widgets/join/ui/bottomSheet.tsx
> +        <div className="w-[40px] h-[4px] items-center rounded-[1000px] bg-[#E0E0E0] mb-spacing-04" />
원석님도 동일하게 framer motion 쓰신 거 같아서 이거 아예 shared 쪽으로 빼주시면 좋을 것 같아요!

2024-10-05 17:30 UTC, tptkds approved these changes

2024-10-05 17:30 UTC, tptkds commented on src/app/join/kakao/page.tsx
경로 세그먼트 내에 있는 page.tsx는 서버컴포넌트로 유지하고 widgets/join-widget/ui/JoinWidget.tsx을 만들어서 임포트하는 방향으로 가는 게 좋을 거 같아요!

2024-10-05 17:30 UTC, tptkds commented on src/app/join/kakao/page.tsx
> +          onClick={() => {
사용자를 navigate 시키는 대신 state에 따라서 UI만 바꾸는 게 좋을 거 같아요!

join-widgets/hooks/useJoin.ts 를 만들고, step,  role(owner, employee), loginProvider(apple, email, kakao) 등의 state를 그 안에 만들어서 관리하면 UI 컴포넌트를 분기 처리해 주면 되니까 현재처럼 중복 코드 문제를 해결할 수 있을 거 같아요.

2024-10-05 17:30 UTC, tptkds commented on src/app/join/kakao/page.tsx
> +          onClick={() => {
사용자를 navigate 시킬 때는 Link 컴포넌트를 사용해 주시는 게 좋습니다!
prefetching 기능이 있어 Link컴포넌트가 뷰포트에 나타나면  참조된 페이지의 렌더링에 필요한 리소스를 백그라운드에서 다운로드 받아 와요.

지금처럼 사용자가 누를 가능성이 높은 경우에는 prefetching을 해 주는 게 맞는 거 같습니다.
꼭 button을 사용해야 할 때는 router.prefetch()를 사용해서 prefetching해 주시면 됩니다.

2024-10-05 17:30 UTC, tptkds commented on src/widgets/index.ts
이거는 제가 FSD 아키텍처 구성할 때 만들었어요.
 src/레이어 폴더/index.ts는 해당 레이어에 있는 파일들을 밖으로 export할 때 사용하려고 만든 거예요!
각 레이어의 단일 entry point에서 import 하기 위해 필요합니다.

2024-10-06 12:19 UTC, yerim08 commented on src/app/join/phone/page.tsx
네! 제가 이 부분을 늦게 확인해서 수정하지 못하고 올렸습니당

2024-10-06 12:25 UTC, yerim08 commented on src/features/join/utils/getRandomColor.tsx
> +  | undefined {
아니요 colors에 있는 값만 반환돼요!

2024-10-06 12:26 UTC, yerim08 commented on src/features/join/utils/getRandomColor.tsx
> +  | undefined {
처음에 colors에 있는 값들만 적어주었는데 제가 쓰려는 컴포넌트에서 함수를 사용하려고 하니 타입 오류가 발생하더라구요 그래서 전체 값을 다 적어줬습니다

2024-10-07 13:30 UTC, iOdiO89 approved these changes

2024-10-07 13:30 UTC, merged