FIX: 얼루가게 직원 관리 화면 퍼블리싱 수정
the-kingdoms/eollugage-fe pull request #24
Opened 2024-10-11 08:00 UTC by tptkds

## #️연관된 이슈

> #21 

## 작업 내용

- 근무 날짜: Date Input -> Button Drawar로 수정
- 근무 시간: Time Input -> text Input으로 수정
  - zod 스키마 수정(HH:mm형식 검증)
- 근무 수정 페이지 추가 (/manage/edit-attendance/[id]
    - 근무 추가 Form 재사용

### 스크린샷
<img width="495" alt="스크린샷 2024-10-11 오후 4 49 04" src="https://github.com/user-attachments/assets/9b878de5-946c-44b3-b733-85c55e80dd30">
<img width="514" alt="스크린샷 2024-10-11 오후 4 53 20" src="https://github.com/user-attachments/assets/9fa2308f-668d-4cf9-987a-7f6decef89fe">
<img width="514" alt="스크린샷 2024-10-11 오후 4 54 02" src="https://github.com/user-attachments/assets/b6c44ab0-0342-42f8-a28b-91cf962a8d3d">

2024-10-11 16:03 UTC, iOdiO89 requested changes
일부 수정사항이 있습니다! 반영 부탁드립니다 😀

2024-10-11 16:03 UTC, iOdiO89 commented on src/widgets/work-management/ui/ViewModeToggle.tsx
> +      <ViewModeToggleChip
![image](https://github.com/user-attachments/assets/264848fb-0155-4ab1-8b36-e8fe4fddc6fb)

togglechip border radius가 적용이 안 되는 것 같습니다. 변경 부탁드립니다
border radius: `rounded-radius-02`
font color: `${isActivated ? 'bg-white ' : 'bg-[#E0E0E0] text-text-disabled'}`

2024-10-14 07:54 UTC, tptkds commented on src/widgets/attendance-form/ui/SelectWorkingTime.tsx
>              />
1,2번은 수정했습니다.

3,4번은 말씀 주신 것처럼 ux측면에서 변경하는 게 더 좋을 거 같아 피그마에 먼저 코멘트 남겨보고, 기획자분 확인 후 수정 진행하겠습니다!

2024-10-14 08:07 UTC, tptkds commented
@iOdiO89 
코멘트 남겨 주신 것 중 근무 시간 입력 방식 변경 제외한 나머지는 반영이 완료되었습니다. 확인 부탁드립니다!

2024-10-14 10:28 UTC, PangKiYeon reviewed
LGTM

<img width="404" alt="스크린샷 2024-10-14 오후 7 17 09" src="https://github.com/user-attachments/assets/f63d2e46-ccd5-48bd-9424-7d13ac402c9b">

이 부분만 폰트가 피그마와 달라서 수정해주시면 될 것 같습니다!
늦은 리뷰 죄송합니다..

2024-10-14 11:22 UTC, tptkds commented
> LGTM
> 
> <img alt="스크린샷 2024-10-14 오후 7 17 09" width="404" src="https://private-user-images.githubusercontent.com/132427506/376200872-f63d2e46-ccd5-48bd-9424-7d13ac402c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDUwNTYsIm5iZiI6MTcyODkwNDc1NiwicGF0aCI6Ii8xMzI0Mjc1MDYvMzc2MjAwODcyLWY2M2QyZTQ2LWNjZDUtNDhiZC05NDI0LTdkMTNhYzQwMmM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTE5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmQ3NjRmMGZjMzQxODc3YjlhNTk0Y2Q5NDFhMTU0ODhmZDA5MGZmMGIwMzJkMTYyOTlmNTY4YjU2Y2NjYjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t0Hd4za-19ckYlEkD8TJM8oA1TFywW32PrlUHddZ7M8">
> 이 부분만 폰트가 피그마와 달라서 수정해주시면 될 것 같습니다! 늦은 리뷰 죄송합니다..

body-04-bold 적용했습니다!

2024-10-14 12:30 UTC, iOdiO89 approved these changes
LGTM!

2024-10-14 12:40 UTC, PangKiYeon approved these changes

2024-10-14 12:58 UTC, merged