마이페이지 API 수정 (Fixes #47)
the-kingdoms/eollugage-fe pull request #65
Opened 2024-10-28 04:31 UTC by Wonchang0314

2024-10-28 17:03 UTC, iOdiO89 commented on src/shared/types/myPageTypes.ts
enum 값들은 어디서 가져오신 거에요? 제가 알고 있는 거랑 조금 달라서용

2024-10-28 17:27 UTC, iOdiO89 requested changes
https://github.com/user-attachments/assets/cb391af1-8984-4f9a-941f-87d43435e6a6

직책 변경 스크롤이 안 되는 것 같아요 확인 부탁드립니다 ..!!

이 부분 제외하고는 요구사항에 맞게 잘 수정된 것 같습니다 LGTM

2024-10-28 17:27 UTC, iOdiO89 commented on src/features/mypage/api/getMy.ts
/entities/user 에 fetchUserInfo가 있습니다 그걸 활용하시면 될 것 같습니다~

2024-10-28 17:27 UTC, iOdiO89 commented on src/shared/atoms/globalAtom.ts
> +export const userNameAtom = atom<string>('')
음 그 저번처럼 이전에 삭제했던 내용들이 다시 커밋된 거 보니까 덮어씌우신 것 같아요 ㅠㅠ... 한번 확인해봐주시겠어요? 제가 lint 오류때문에 수정했었는데 오류 안 나면 그대로 가져가도 될 것 같습니다

참고) [오류 수정 커밋](https://github.com/the-kingdoms/eollugage-fe/commit/e742143b25d4bfb999e0c74054697f33f5aaf766#diff-2b276e5138bbb4b672a3301ee701845c87ef29e1c6dda0d3097e91f8248b1ec4)

2024-10-28 17:27 UTC, iOdiO89 commented on src/shared/types/myPageTypes.ts
> +}
이 부분도 /entities/user/types 에 있었던 것 같아요

2024-10-29 00:14 UTC, Wonchang0314 commented on src/features/mypage/api/getMy.ts
넵

2024-10-29 00:22 UTC, Wonchang0314 commented on src/shared/atoms/globalAtom.ts
> +export const userNameAtom = atom<string>('')
아 이거 제가 필요할거 같아서 추가해놓은것들인데 필요없나요?

2024-10-29 00:22 UTC, Wonchang0314 commented on src/shared/types/myPageTypes.ts
말씀하신걸로 수정했습니다

2024-10-29 01:20 UTC, Wonchang0314 commented on src/shared/atoms/globalAtom.ts
> +export const userNameAtom = atom<string>('')
린트오류 안나서 일단 냅두겠습니다

2024-10-31 11:53 UTC, iOdiO89 approved these changes

2024-10-31 11:53 UTC, merged