FEAT: 마이페이지, 설정 화면 퍼블리싱
the-kingdoms/eollugage-fe pull request #9
Opened 2024-10-02 08:59 UTC by Wonchang0314

오류는 아니고 개발하면서 느낀 얼루가 컴포넌트 수정사항입니다.

SnackBar : 원하는 아이콘으로 변경가능하게끔 수정
ButtonMobile : 백그라운드 색깔을 props로 바꿀 수 있게끔 수정할 필요 있어보임
+ 추가로 TopBar 컴포넌트의 아이콘 크기를 조정할 수 있도록 props가 있다면 더 좋을 것 같긴함 (지금 기본값이 좀 작은 거 같은 느낌)

2024-10-04 16:47 UTC, iOdiO89 requested changes
1. tailwindcss 에서 여러 종류를 혼용해서 쓰고 계신 것 같습니다. 최대한 통일해서 작성해주세요!
- ex) `p-[4px]` vs `p-1` vs `p-spacing-01`
- ex) `bg-Gray-100` vs `bg-support-info`

2. 제가 파일마다 코멘트를 다 달진 않았는데요,
파일 위치는 일단 가장 바깥에 위치한 원래 있던 폴더들 안으로 변경해주세요! eolluga-fe 리드미랑 FSD 아키텍쳐 관련해서 구글링을 좀 해보시면 이해가 될 것 같습니당. 아니면 유경님이 잘 알고 계셔서 유경님께 여쭤보셔요!!
+ 특히 /app 폴더 안에는 필요한 페이지들만 남기고 컴포넌트들은 다른 폴더로 옮겨주세요

- SSR/CSR , FSD 아키텍쳐에 대해 찾아보시면 도움이 될 것 같습니다 😀

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/bottomSheet.tsx
> +        className="bg-white w-full rounded-t-lg p-6 h-[90vh]"
바텀시트 전체 높이를 90vh로 잡았기 때문에 
- 가게 직책~매니저 부분까지 하나의 큰 div 
- 하단의 Input
바텀시트 안쪽을 크게 두개의 부분으로 나누고 justify-between 하면 78줄에 있는 80%와 같은 임의의 숫자를 없앨 수 있을 것 같습니당

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/page.tsx
> +  const router = useRouter()
페이지레벨에서 userouter를 사용하면 전부 클라이언트 사이드가 되어버려서 구조 변경이 필요할 것 같습니닷

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/position.tsx
오 !! 완전 잘 되는 것 같습니다 ㅎㅎ 그런데 setting은 따로 페이지로 분리하시고 position은 컴포넌트처럼 두신 이유가 있나요? 이것도 아예 페이지로 분리해도 될 것 같아보여서요..!

2024-10-04 16:47 UTC, iOdiO89 commented on src/types/myPageTypes.ts
/shared/types 안으로 가면 좋을 것 같습니다 ㅎㅎ

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/quit.tsx
> +      <footer className="w-full py-3 px-4 fixed bottom-4">
음 footer는 보통 웹하단에 표시해야할 정보들이 있을 때 사용하는데요! footer로 작성하신 이유가 있나요?

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/page.tsx
비슷한 레이아웃이 반복되는 페이지라 컴포넌트화해서 작성하시면 좋을 것 같습니다

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/page.tsx
> +            <ul className="flex flex-col gap-spacing-02 p-4">
px-4 py-2입니다!

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/logoutModal.tsx
얼루가 컴포넌트 중에 dialog 가 있는데 혹시 오류가 있어서 사용 안하신건가요?

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/inquire/page.tsx
> +      {currentView === 'byPhone' && <ByPhonePage handleChangeView={handleChangeView} />}
따로 페이지 분리가 좋을 것 같습니다

2024-10-04 16:47 UTC, iOdiO89 commented on src/app/mypage/setting/inquire/byPhone.tsx
> +        />
전화번호 수정창이 아니라서 textfield 보다 그냥 div로 가는 게 맞을 것 같습니다

2024-10-04 16:47 UTC, iOdiO89 commented on src/component/shared/toastMessage.tsx
이건 제가 폴더를 잘못 만든 것 같아서 /src/shared 안으로 옮겨주실 수 있나요..?!

2024-10-05 03:55 UTC, Wonchang0314 commented on .prettierrc
> +  "printWidth": 90,
저도 120은 좋은데 Eslint에서 100이 넘으면 안된다길래 저렇게 했더니 그 에러는 안뜨긴했습니다

2024-10-05 03:56 UTC, Wonchang0314 commented on src/component/shared/toastMessage.tsx
> +          <Image height={20} width={20} alt="text" src="/image/check-icon.svg" />
이거는 저희 아이콘리스트에 있는 check랑 warning이 피그마 시안이랑 같지 않길래 피그마에서 다운받은 이미지들을 일단 넣어놨습니다.

2024-10-05 03:58 UTC, Wonchang0314 commented on src/app/mypage/setting/logoutModal.tsx
이거는 사소한데 저희 dialog는 폭이 조금 좁은 것 같아서 그냥 저렇게 한번 넣어봤습니다. 
오류는 딱히 없었습니다

2024-10-06 11:44 UTC, tptkds requested changes
우선 컴포넌트 파일에는 파스칼 케이스를 쓰기로 했는데, 반영된 파일이 없는 거 같습니다.

widgets 슬라이스로 관리해야 할 게 setting, inquiry, my page 로 보이는데 지금은 app router 내에 ui 관련된 모든 파일이 위치해 있네요.

각 슬라이스를 만들어서 내부에 관련 컴포넌트, 타입, 유틸, 훅을 옮겨 주시면 좋을 거 같아요.

예를 들어 widgets/setting-widget/ui 에는 SeetingWidget.tsx, Privacy.tsx, Quit.tsx, LogoutModal.tsx, Alarm.tsx, AppInfo.tsx, BusinessInfo.tsx 가 오면 될 거 같고, app/setting/page.tsx에서는 SeetingWidget만 import 해서 렌더링해 주면 됩니다!

2024-10-06 11:44 UTC, tptkds commented on src/app/mypage/setting/page.tsx
widgets/setting-widget/ui/SettingWidget.tsx로 분리한 다음 import 하는 방식으로 가는 게 FSD 아키텍쳐에 맞을 거 같아요.

2024-10-06 11:44 UTC, tptkds commented on src/app/mypage/setting/inquire/page.tsx
이것도 widgets 레이어에 슬라이스 만들어서 관리하는 게 좋을 거 같습니다.

2024-10-06 11:44 UTC, tptkds commented on src/data/privacyPolicy.json
widgets/setting-widget/data로 옮기는 게 좋을 거 같습니다.

2024-10-06 11:44 UTC, tptkds commented on src/types/myPageTypes.ts
마이페이지에서만 쓰이는 타입들이라면 마이페이지 위젯 슬라이스를 한 개 만든 후 types 세그먼트에 넣어 주시면 되고, 다른 곳에서도 쓰일 거 같다면 shared/types에 넣어주시면 좋을 거 같아요!

2024-10-06 16:39 UTC, Wonchang0314 commented on src/app/mypage/setting/page.tsx
안 그래도 이런거 FSD 아키텍처 공부하면서 고민이였는데 참고하겠습니다 감사합니다

2024-10-07 11:05 UTC, Wonchang0314 commented
"arrow-parens": "off",
"object-curly-newline": "off", // 중괄호 줄바꿈 규칙 비활성화
"import/prefer-default-export": "off", // default export 강제하지 않음
"react/jsx-curly-brace-presence": "off",
"max-len": "off",
"react/jsx-no-useless-fragment": "off" // 불필요한 Fragment 사용 허용

저는 이렇게 해야 린트오류가 해결이 되던데, 여기서 꼭 필요한 규칙이 있으면 알려주십쇼

2024-10-07 12:55 UTC, PangKiYeon approved these changes
LGTM

2024-10-07 16:31 UTC, iOdiO89 approved these changes

2024-10-07 17:45 UTC, merged