FEAT: #89 회원가입 인증번호 관련 ui를 추가한다
the-kingdoms/eollugage-fe pull request #94
Opened 2024-12-16 05:46 UTC by Wonchang0314

## #89 

## 작업 내용
저희 얼루가 컴포넌트 임포트 방식이 바뀐게 아직 적용되어 있지 않는거 같아서 로컬에서 검증은 아직 못해보고
대강 흐름만 검증받고자 PR올립니다.

2024-12-16 06:17 UTC, iOdiO89 commented
얼루가 컴포넌트 버전을 3.2.9로 내려서 해보시겠어요? 3.2.9가 적용되어 있는 버전입니다

2024-12-16 12:56 UTC, iOdiO89 commented
1. 전화번호, 인증번호 value값이 동일한 것 같습니다. 전화번호를 입력하니까 인증번호 값도 같이 변경돼요
<img width="588" alt="image" src="https://github.com/user-attachments/assets/130e355b-19d3-4124-9d4f-77b08a45e4a6" />


2. 회원가입 초기 화면에 들어왔을 때 인증번호 Textfield가 에러상태로 떠 있습니다
<img width="592" alt="image" src="https://github.com/user-attachments/assets/ffd7d838-935d-4dca-84fd-69ca6207418a" />


 같이 수정부탁드립니다 😀!

2024-12-17 13:08 UTC, Wonchang0314 commented
1. 얼루가 컴포넌트 버전을 3.2.9로 내렸습니다.
2. 오류도 수정해놨습니다. 
3. 로컬에서 테스트해봤을때는 잘 되는 것 같습니다

2024-12-18 14:33 UTC, iOdiO89 requested changes
1. 전화번호 입력 후 인증번호 받기 버튼을 눌렀을 때 전화번호 유효성 검사가 빠져있는 것 같아요. 
자체적으로 전화번호 유효성 검사 + send-verification-code api 404 반환시 error 처리가 추가적으로 필요할 것 같습니다!

2. 전화번호 입력 -> 인증번호 입력 -> 전화번호 변경이 가능한 것 같아요.
인증번호를 받았는데 다시 전화번호를 변경하는 경우, 버튼이 다시 인증번호 받기로 바뀌어야 할 것 같습니당

2024-12-19 15:45 UTC, Wonchang0314 commented
1. 말씀해주신대로 전화번호 자체 검증 및 에러처리 로직 추가해봤습니다
2. 전화번호를 다시 입력할때 초기화 인증번호 받기로 다시 초기화되게끔 수정해놨습니다

2024-12-20 03:49 UTC, iOdiO89 commented
LGTM! 좋은 것 같습니다

피그마 확인해보니까 전화번호 유효성 검사 실패했을 때 textfield error만 뜨고, Toast는 따로 안 뜨는 거로 되어 있어서
그 부분만 제가 수정했습니당

2024-12-20 03:51 UTC, iOdiO89 approved these changes

2024-12-20 03:52 UTC, merged